import asyncio
from logging.config import fileConfig

from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from alembic import context

# Import Base so Alembic can see all registered ORM models via Base.metadata.
# When new ORM model files are added (Phase 1+), import them below so their
# tables appear in autogenerated migrations.
from app.config import get_settings
from app.database import Base  # noqa: F401

# Domain model imports — required so Alembic registers their tables in Base.metadata.
import app.models.lead  # noqa: F401
import app.models.listing  # noqa: F401
import app.models.session  # noqa: F401
import app.models.conversation  # noqa: F401

config = context.config
settings = get_settings()

# Override alembic.ini's empty sqlalchemy.url with the value from app settings.
# This keeps the database URL in one place: the .env file / config.py.
config.set_main_option("sqlalchemy.url", settings.database_url)

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """Generate SQL script without a live DB connection (--sql flag)."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(connection=connection, target_metadata=target_metadata)
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    engine = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,  # No pooling for migration runs — each is a one-shot operation
    )
    async with engine.connect() as connection:
        await connection.run_sync(do_run_migrations)
    await engine.dispose()


def run_migrations_online() -> None:
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
